"""TradingView fundamentals field catalog — GENERATED, do not edit by hand.

Regenerate with::

    uv run python scripts/gen_fundamentals_catalog.py \
        tests/fixtures/fundamentals/config_v2.json tvkit/api/fundamentals/catalog.py

Derived from TradingView's ``fundamentals_config_v2`` dictionary. Maps each statement to the
set of period-stripped field-id bases to request and the per-template display order. See
``docs/concepts/financial-statements.md``.
"""

from __future__ import annotations

# Statement period suffixes appended to a base id (history arrays use the ``_h`` variant).
PERIOD_SUFFIX: dict[str, str] = {
    "FY": "fy",
    "FQ": "fq",
    "FH": "fh",
    "TTM": "ttm",
}

# Structural fields (NOT in the config dictionary) that align history arrays to periods and
# carry currency/template metadata. Requested with every statement snapshot.
PERIOD_FIELDS: dict[str, list[str]] = {
    "FY": ["fiscal_period_fy_h", "fiscal_period_end_fy_h"],
    "FQ": ["fiscal_period_fq_h", "fiscal_period_end_fq_h"],
    "FH": ["fiscal_period_fh_h", "fiscal_period_end_fh_h"],
    "TTM": ["fiscal_period_fq_h", "fiscal_period_end_fq_h"],
}
META_FIELDS: list[str] = ["fundamental_currency_code", "currency_code", "report_type"]

# Revenue segments (P0) — structural quote fields, not in the config dictionary.
SEGMENT_FIELDS: list[str] = ["revenue_seg_by_business_h", "revenue_seg_by_region_h"]

# Dividend events history + summary (aligned to each other, not to fiscal periods).
DIVIDEND_EVENT_FIELDS: list[str] = [
    "dividend_amount_h",
    "dividend_ex_date_h",
    "dividend_payment_date_h",
    "dividend_record_date_h",
    "dividend_type_h",
]
DIVIDEND_SUMMARY_FIELDS: list[str] = [
    "dividend_amount_recent",
    "dividend_ex_date_recent",
    "dividend_payment_date_recent",
    "dividend_yield_recent",
    "dividends_paid",
    "dividend_payout_ratio_ttm",
    "dividend_payout_ratio_fy_h",
    "dividends_availability",
]

# Earnings — reported vs estimate + surprise, keyed by earnings/estimates period arrays.
EARNINGS_FIELDS: dict[str, list[str]] = {
    "FQ": [
        "earnings_per_share_fq_h",
        "earnings_per_share_diluted_fq_h",
        "earnings_estimate_fq_h",
        "earnings_per_share_forecast_fq_h",
        "revenues_fq_h",
        "revenues_estimate_fq_h",
        "earnings_fiscal_period_fq_h",
        "earnings_release_date_fq_h",
    ],
    "FY": [
        "earnings_per_share_fy_h",
        "earnings_per_share_diluted_fy_h",
        "earnings_estimate_fy_h",
        "earnings_per_share_forecast_fy_h",
        "revenues_fy_h",
        "revenues_estimate_fy_h",
        "earnings_fiscal_period_fy_h",
        "earnings_release_date_fy_h",
    ],
}

# {statement: [base field ids to request]} — union across templates.
STATEMENT_REQUEST_FIELDS: dict[str, list[str]] = {
    "income": [
        "after_tax_other_income",
        "basic_shares_outstanding",
        "cost_of_goods",
        "diluted_net_income",
        "diluted_shares_outstanding",
        "dilution_adjustment",
        "discontinued_operations",
        "earnings_per_share_basic",
        "earnings_per_share_diluted",
        "ebit",
        "ebitda",
        "equity_in_earnings",
        "gross_profit",
        "income_from_cont_ops",
        "income_tax",
        "interest_expense",
        "interest_income_net",
        "loan_loss_provision",
        "minority_interest_exp",
        "net_income",
        "net_income_bef_disc_oper",
        "net_revenue",
        "net_revenue_after_provision",
        "non_interest_expense",
        "non_interest_income",
        "non_oper_income",
        "oper_income",
        "operating_expenses",
        "preferred_dividends",
        "pretax_income",
        "total_non_oper_income",
        "total_oper_expense",
        "total_revenue",
        "unusual_expense_inc",
    ],
    "statistics": [
        "asset_turnover",
        "book_tangible_per_share",
        "book_value_per_share",
        "capex_per_share",
        "cash_n_due_f_banks_total_deposits",
        "cash_per_share",
        "combined_ratio",
        "common_equity_tier1_ratio",
        "common_equity_total_deposits",
        "current_ratio",
        "debt_to_asset",
        "debt_to_equity",
        "demand_deposits_total_deposits",
        "ebit_per_share",
        "ebitda_margin",
        "ebitda_per_share",
        "enterprise_value",
        "enterprise_value_ebit_fwd",
        "enterprise_value_ebitda",
        "enterprise_value_ebitda_fwd",
        "enterprise_value_sales_fwd",
        "equity_ratio",
        "expense_ratio",
        "float_shares_outstanding",
        "free_cash_flow_per_share",
        "gross_margin",
        "interest_expense_ib_liabs",
        "interest_income_avg_total_deposits",
        "interest_income_earn_assets",
        "invent_turnover",
        "invested_assets_n_loans_net_total_deposits",
        "invested_assets_total_assets",
        "invested_assets_total_deposits",
        "life_ins_in_force",
        "loan_loss_coverage",
        "loan_loss_rsrv_loans_gross",
        "loan_loss_rsrv_total_assets",
        "loan_loss_rsrv_total_capital",
        "loan_losses_act_loan_loss_rsrv",
        "loan_losses_act_loans_gross",
        "loans_gross_total_assets",
        "loans_gross_total_deposits",
        "long_term_debt_to_assets",
        "long_term_debt_to_equity",
        "loss_ratio",
        "ncavps_ratio",
        "net_margin",
        "non_interest_income_revenue",
        "nonperf_loan_common_equity",
        "nonperf_loans_loan_loss_rsrv",
        "nonperf_loans_loans_gross",
        "number_of_employees",
        "number_of_shareholders",
        "operating_cash_flow_per_share",
        "operating_margin",
        "price_book",
        "price_book_fwd",
        "price_cash_flow",
        "price_earnings",
        "price_earnings_fwd",
        "price_sales",
        "price_sales_fwd",
        "quick_ratio",
        "reserve_to_total_capital",
        "return_on_assets",
        "return_on_equity",
        "return_on_invested_capital",
        "revenue_per_share",
        "savings_time_deposits_total_deposits",
        "tier1_capital_ratio",
        "tier2_capital_ratio",
        "total_capital_ratio",
        "total_debt_per_share",
        "total_deposits_total_assets",
        "total_shares_outstanding",
        "unearned_premium_to_total_capital",
        "working_capital_per_share",
    ],
    "cash_flow": [
        "cash_f_financing_activities",
        "cash_f_investing_activities",
        "cash_f_operating_activities",
        "cash_interest_paid",
        "cash_taxes_paid",
        "foreign_exch_effects",
        "free_cash_flow",
        "misc_funds",
        "net_chg_in_cash",
    ],
    "balance": [
        "common_equity_tier1",
        "loan_losses_act",
        "loan_losses_net",
        "net_debt",
        "nonperf_loans",
        "risk_weighted_assets",
        "tier1_capital",
        "tier2_capital",
        "total_assets",
        "total_debt",
        "total_equity",
        "total_liabilities",
        "total_liabilities_shrhldrs_equity",
    ],
}

# {statement: {fund_view_mode: [base ids in display order]}}.
STATEMENT_ORDER: dict[str, dict[str, list[str]]] = {
    "income": {
        "banking": [
            "net_revenue",
            "interest_income_net",
            "non_interest_income",
            "loan_loss_provision",
            "net_revenue_after_provision",
            "non_interest_expense",
            "oper_income",
            "non_oper_income",
            "unusual_expense_inc",
            "pretax_income",
            "income_tax",
            "income_from_cont_ops",
            "discontinued_operations",
            "equity_in_earnings",
            "minority_interest_exp",
            "after_tax_other_income",
            "net_income",
            "total_revenue",
            "dilution_adjustment",
            "preferred_dividends",
            "diluted_net_income",
            "earnings_per_share_basic",
            "earnings_per_share_diluted",
            "basic_shares_outstanding",
            "diluted_shares_outstanding",
        ],
        "industrial": [
            "total_revenue",
            "cost_of_goods",
            "gross_profit",
            "operating_expenses",
            "oper_income",
            "total_non_oper_income",
            "pretax_income",
            "equity_in_earnings",
            "income_tax",
            "minority_interest_exp",
            "after_tax_other_income",
            "net_income_bef_disc_oper",
            "discontinued_operations",
            "net_income",
            "dilution_adjustment",
            "preferred_dividends",
            "diluted_net_income",
            "earnings_per_share_basic",
            "earnings_per_share_diluted",
            "basic_shares_outstanding",
            "diluted_shares_outstanding",
            "ebitda",
            "ebit",
            "total_oper_expense",
        ],
        "insurance": [
            "total_revenue",
            "total_oper_expense",
            "oper_income",
            "total_non_oper_income",
            "pretax_income",
            "equity_in_earnings",
            "income_tax",
            "minority_interest_exp",
            "after_tax_other_income",
            "net_income_bef_disc_oper",
            "discontinued_operations",
            "net_income",
            "dilution_adjustment",
            "preferred_dividends",
            "diluted_net_income",
            "earnings_per_share_basic",
            "earnings_per_share_diluted",
            "basic_shares_outstanding",
            "diluted_shares_outstanding",
        ],
        "other": [
            "total_revenue",
            "total_oper_expense",
            "oper_income",
            "non_oper_income",
            "interest_expense",
            "unusual_expense_inc",
            "pretax_income",
            "income_tax",
            "equity_in_earnings",
            "after_tax_other_income",
            "minority_interest_exp",
            "net_income_bef_disc_oper",
            "preferred_dividends",
            "net_income",
            "earnings_per_share_basic",
            "earnings_per_share_diluted",
            "basic_shares_outstanding",
            "diluted_shares_outstanding",
            "ebitda",
            "ebit",
        ],
    },
    "statistics": {
        "banking": [
            "total_shares_outstanding",
            "float_shares_outstanding",
            "number_of_employees",
            "number_of_shareholders",
            "price_earnings",
            "price_sales",
            "price_cash_flow",
            "price_book",
            "enterprise_value",
            "price_sales_fwd",
            "price_earnings_fwd",
            "price_book_fwd",
            "enterprise_value_sales_fwd",
            "return_on_assets",
            "return_on_equity",
            "return_on_invested_capital",
            "operating_margin",
            "net_margin",
            "non_interest_income_revenue",
            "interest_income_avg_total_deposits",
            "interest_income_earn_assets",
            "interest_expense_ib_liabs",
            "current_ratio",
            "asset_turnover",
            "cash_n_due_f_banks_total_deposits",
            "loan_loss_rsrv_loans_gross",
            "nonperf_loan_common_equity",
            "nonperf_loans_loan_loss_rsrv",
            "nonperf_loans_loans_gross",
            "demand_deposits_total_deposits",
            "loan_losses_act_loans_gross",
            "loan_losses_act_loan_loss_rsrv",
            "loan_loss_coverage",
            "debt_to_asset",
            "debt_to_equity",
            "long_term_debt_to_assets",
            "long_term_debt_to_equity",
            "total_deposits_total_assets",
            "loans_gross_total_assets",
            "invested_assets_total_assets",
            "loan_loss_rsrv_total_assets",
            "common_equity_total_deposits",
            "invested_assets_total_deposits",
            "invested_assets_n_loans_net_total_deposits",
            "loans_gross_total_deposits",
            "loan_loss_rsrv_total_capital",
            "savings_time_deposits_total_deposits",
            "revenue_per_share",
            "operating_cash_flow_per_share",
            "free_cash_flow_per_share",
            "book_value_per_share",
            "total_debt_per_share",
            "cash_per_share",
            "ncavps_ratio",
            "book_tangible_per_share",
            "working_capital_per_share",
            "capex_per_share",
            "tier1_capital_ratio",
            "tier2_capital_ratio",
            "total_capital_ratio",
            "common_equity_tier1_ratio",
        ],
        "industrial": [
            "total_shares_outstanding",
            "float_shares_outstanding",
            "number_of_employees",
            "number_of_shareholders",
            "price_earnings",
            "price_sales",
            "price_cash_flow",
            "price_book",
            "enterprise_value",
            "enterprise_value_ebitda",
            "price_sales_fwd",
            "price_earnings_fwd",
            "price_book_fwd",
            "enterprise_value_ebitda_fwd",
            "enterprise_value_ebit_fwd",
            "enterprise_value_sales_fwd",
            "return_on_assets",
            "return_on_equity",
            "return_on_invested_capital",
            "gross_margin",
            "operating_margin",
            "ebitda_margin",
            "net_margin",
            "quick_ratio",
            "current_ratio",
            "invent_turnover",
            "asset_turnover",
            "debt_to_asset",
            "debt_to_equity",
            "long_term_debt_to_assets",
            "long_term_debt_to_equity",
            "revenue_per_share",
            "operating_cash_flow_per_share",
            "free_cash_flow_per_share",
            "ebit_per_share",
            "ebitda_per_share",
            "book_value_per_share",
            "total_debt_per_share",
            "cash_per_share",
            "ncavps_ratio",
            "book_tangible_per_share",
            "working_capital_per_share",
            "capex_per_share",
        ],
        "insurance": [
            "total_shares_outstanding",
            "float_shares_outstanding",
            "number_of_employees",
            "number_of_shareholders",
            "price_earnings",
            "price_sales",
            "price_cash_flow",
            "price_book",
            "enterprise_value",
            "price_sales_fwd",
            "price_earnings_fwd",
            "price_book_fwd",
            "enterprise_value_ebit_fwd",
            "enterprise_value_sales_fwd",
            "return_on_assets",
            "return_on_equity",
            "return_on_invested_capital",
            "operating_margin",
            "net_margin",
            "loss_ratio",
            "expense_ratio",
            "combined_ratio",
            "current_ratio",
            "asset_turnover",
            "reserve_to_total_capital",
            "unearned_premium_to_total_capital",
            "debt_to_asset",
            "debt_to_equity",
            "long_term_debt_to_assets",
            "long_term_debt_to_equity",
            "equity_ratio",
            "revenue_per_share",
            "operating_cash_flow_per_share",
            "free_cash_flow_per_share",
            "book_value_per_share",
            "total_debt_per_share",
            "cash_per_share",
            "ncavps_ratio",
            "book_tangible_per_share",
            "working_capital_per_share",
            "capex_per_share",
            "life_ins_in_force",
        ],
        "other": [
            "total_shares_outstanding",
            "float_shares_outstanding",
            "number_of_employees",
            "number_of_shareholders",
            "price_earnings",
            "price_sales",
            "price_cash_flow",
            "price_book",
            "enterprise_value",
            "enterprise_value_ebitda",
            "price_sales_fwd",
            "price_earnings_fwd",
            "price_book_fwd",
            "enterprise_value_ebitda_fwd",
            "enterprise_value_ebit_fwd",
            "enterprise_value_sales_fwd",
            "return_on_assets",
            "return_on_equity",
            "return_on_invested_capital",
            "gross_margin",
            "operating_margin",
            "ebitda_margin",
            "net_margin",
            "asset_turnover",
            "debt_to_asset",
            "debt_to_equity",
            "long_term_debt_to_assets",
            "long_term_debt_to_equity",
            "revenue_per_share",
            "operating_cash_flow_per_share",
            "free_cash_flow_per_share",
            "ebit_per_share",
            "ebitda_per_share",
            "book_value_per_share",
            "total_debt_per_share",
            "cash_per_share",
            "ncavps_ratio",
            "book_tangible_per_share",
            "working_capital_per_share",
            "capex_per_share",
        ],
    },
    "cash_flow": {
        "banking": [
            "cash_f_operating_activities",
            "cash_f_investing_activities",
            "cash_f_financing_activities",
            "foreign_exch_effects",
            "misc_funds",
            "net_chg_in_cash",
            "free_cash_flow",
        ],
        "industrial": [
            "cash_f_operating_activities",
            "cash_f_investing_activities",
            "cash_f_financing_activities",
            "free_cash_flow",
        ],
        "insurance": [
            "cash_f_operating_activities",
            "cash_f_investing_activities",
            "cash_f_financing_activities",
            "free_cash_flow",
        ],
        "other": [
            "cash_f_operating_activities",
            "cash_f_investing_activities",
            "cash_f_financing_activities",
            "foreign_exch_effects",
            "misc_funds",
            "net_chg_in_cash",
            "free_cash_flow",
            "cash_interest_paid",
            "cash_taxes_paid",
        ],
    },
    "balance": {
        "banking": [
            "total_assets",
            "total_liabilities",
            "total_equity",
            "total_liabilities_shrhldrs_equity",
            "common_equity_tier1",
            "tier1_capital",
            "tier2_capital",
            "risk_weighted_assets",
            "nonperf_loans",
            "loan_losses_act",
            "loan_losses_net",
        ],
        "industrial": [
            "total_assets",
            "total_liabilities",
            "total_equity",
            "total_liabilities_shrhldrs_equity",
            "total_debt",
            "net_debt",
        ],
        "insurance": [
            "total_assets",
            "total_liabilities",
            "total_equity",
            "total_liabilities_shrhldrs_equity",
            "net_debt",
        ],
        "other": [
            "total_assets",
            "total_liabilities",
            "total_equity",
            "total_liabilities_shrhldrs_equity",
            "net_debt",
        ],
    },
}

# {base field id: display label}.
FIELD_LABELS: dict[str, str] = {
    "after_tax_other_income": "After tax other income/expense",
    "asset_turnover": "Asset turnover",
    "basic_shares_outstanding": "Average basic shares outstanding",
    "book_tangible_per_share": "Tangible book value per share",
    "book_value_per_share": "Book value per share",
    "capex_per_share": "CapEx per share",
    "cash_f_financing_activities": "Cash flow from financing activities",
    "cash_f_investing_activities": "Cash flow from investing activities",
    "cash_f_operating_activities": "Cash flow from operating activities",
    "cash_n_due_f_banks_total_deposits": "Cash & securities to total deposits",
    "cash_per_share": "Cash per share",
    "common_equity_tier1": "Common equity tier 1",
    "common_equity_tier1_ratio": "Common equity tier 1 ratio %",
    "common_equity_total_deposits": "Common equity to total deposits",
    "current_ratio": "Current ratio",
    "debt_to_asset": "Debt to assets ratio",
    "debt_to_equity": "Debt to equity ratio",
    "demand_deposits_total_deposits": "Demand deposits to total deposits",
    "diluted_net_income": "Diluted net income available to common stockholders",
    "diluted_shares_outstanding": "Diluted shares outstanding",
    "dilution_adjustment": "Dilution adjustment",
    "discontinued_operations": "Discontinued operations",
    "earnings_per_share_basic": "Basic earnings per share (basic EPS)",
    "earnings_per_share_diluted": "Diluted earnings per share (diluted EPS)",
    "enterprise_value": "Enterprise value",
    "enterprise_value_sales_fwd": "Enterprise value to revenue forward",
    "equity_in_earnings": "Equity in earnings",
    "float_shares_outstanding": "Free float",
    "foreign_exch_effects": "Exchange rate effect",
    "free_cash_flow": "Free cash flow",
    "free_cash_flow_per_share": "Free cash flow per share",
    "income_from_cont_ops": "Net income from continuing operations",
    "income_tax": "Taxes",
    "interest_expense_ib_liabs": "Total interest expense to interest bearing liabs %",
    "interest_income_avg_total_deposits": "Net interest income to average total deposits %",
    "interest_income_earn_assets": "Net interest income to earning assets %",
    "interest_income_net": "Net interest income",
    "invested_assets_n_loans_net_total_deposits": "Invested assets and net loans to total deposits",
    "invested_assets_total_assets": "Invested assets to total assets",
    "invested_assets_total_deposits": "Invested assets to total deposits",
    "loan_loss_coverage": "Loan loss coverage ratio",
    "loan_loss_provision": "Provision for credit losses",
    "loan_loss_rsrv_loans_gross": "Loan losses reserves to total loans",
    "loan_loss_rsrv_total_assets": "Loan loss reserves to total assets",
    "loan_loss_rsrv_total_capital": "Loan loss reserves to total capital",
    "loan_losses_act": "Loan losses (actual)",
    "loan_losses_act_loan_loss_rsrv": "Loan losses (actual) to loan loss reserve",
    "loan_losses_act_loans_gross": "Loan losses (actual) to total loans",
    "loan_losses_net": "Net loan losses",
    "loans_gross_total_assets": "Gross loans to total assets",
    "loans_gross_total_deposits": "Gross loans to total deposits",
    "long_term_debt_to_assets": "Long term debt to total assets ratio",
    "long_term_debt_to_equity": "Long term debt to total equity ratio",
    "minority_interest_exp": "Non-controlling/minority interest",
    "misc_funds": "Miscellaneous funds",
    "ncavps_ratio": "Net current asset value per share",
    "net_chg_in_cash": "Net change in cash",
    "net_income": "Net income",
    "net_margin": "Net margin %",
    "net_revenue_after_provision": "Net revenue after provisions",
    "net_revenue": "Net revenue",
    "non_interest_expense": "Non-interest expense",
    "non_interest_income": "Non-interest income",
    "non_interest_income_revenue": "Non-interest income to total revenue %",
    "non_oper_income": "Non-operating income (excl. interest expenses)",
    "nonperf_loan_common_equity": "Non-performing loans to common equity",
    "nonperf_loans": "Nonperforming loans (NPLs)",
    "nonperf_loans_loan_loss_rsrv": "Non-performing loans to loan loss reserves",
    "nonperf_loans_loans_gross": "Non-performing loans to total loans",
    "number_of_employees": "Number of employees",
    "number_of_shareholders": "Number of shareholders",
    "oper_income": "Operating income",
    "operating_cash_flow_per_share": "Operating cash flow per share",
    "operating_margin": "Operating margin %",
    "preferred_dividends": "Preferred dividends",
    "pretax_income": "Pretax income",
    "price_book": "Price to book ratio",
    "price_book_fwd": "Price to book forward",
    "price_cash_flow": "Price to cash flow ratio",
    "price_earnings": "Price to earnings ratio",
    "price_earnings_fwd": "Price to earnings forward",
    "price_sales": "Price to sales ratio",
    "price_sales_fwd": "Price to sales forward",
    "return_on_assets": "Return on assets %",
    "return_on_equity": "Return on equity %",
    "return_on_invested_capital": "Return on invested capital %",
    "revenue_per_share": "Revenue per share",
    "risk_weighted_assets": "Risk weighted assets",
    "savings_time_deposits_total_deposits": "Savings deposits to total deposits",
    "tier1_capital": "Tier 1 capital",
    "tier1_capital_ratio": "Tier 1 capital ratio %",
    "tier2_capital": "Tier 2 capital",
    "tier2_capital_ratio": "Tier 2 capital ratio %",
    "total_assets": "Total assets",
    "total_capital_ratio": "Total capital ratio %",
    "total_debt_per_share": "Total debt per share",
    "total_deposits_total_assets": "Total deposits to total assets",
    "total_equity": "Total equity",
    "total_liabilities": "Total liabilities",
    "total_liabilities_shrhldrs_equity": "Total liabilities & shareholders' equities",
    "total_revenue": "Total revenue",
    "total_shares_outstanding": "Total common shares outstanding",
    "unusual_expense_inc": "Unusual income/expense",
    "working_capital_per_share": "Working capital per share",
    "cost_of_goods": "Cost of goods sold",
    "ebit": "EBIT",
    "ebit_per_share": "EBIT per share",
    "ebitda": "EBITDA",
    "ebitda_margin": "EBITDA margin %",
    "ebitda_per_share": "EBITDA per share",
    "enterprise_value_ebit_fwd": "Enterprise value to EBIT forward",
    "enterprise_value_ebitda": "Enterprise value to EBITDA ratio",
    "enterprise_value_ebitda_fwd": "Enterprise value to EBITDA forward",
    "gross_margin": "Gross margin %",
    "gross_profit": "Gross profit",
    "invent_turnover": "Inventory turnover",
    "net_debt": "Net debt",
    "net_income_bef_disc_oper": "Net income before discontinued operations",
    "operating_expenses": "Operating expenses (excl. COGS)",
    "quick_ratio": "Quick ratio",
    "total_debt": "Total debt",
    "total_non_oper_income": "Non-operating income (total)",
    "total_oper_expense": "Total operating expenses",
    "combined_ratio": "Combined ratio %",
    "equity_ratio": "Equity ratio",
    "expense_ratio": "Expense ratio %",
    "life_ins_in_force": "Life Insurance In Force",
    "loss_ratio": "Loss ratio %",
    "reserve_to_total_capital": "Benefit & loss reserve to total capital %",
    "unearned_premium_to_total_capital": "Unearned premium to total capital %",
    "cash_interest_paid": "Interest paid",
    "cash_taxes_paid": "Taxes paid",
    "interest_expense": "Total interest expense (banks)",
}
